---
abstract: 'Determine whether a string consists of well-formed UTF-8 byte sequences'
author:
  - 'Christian Hansen, <chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: String::UTF8
name: String-UTF8
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-UTF8
  license: http://dev.perl.org/licenses/
version: 0.1
